name: nfce
services:
  api:
    build:
      context: .
    restart: always
    expose:
      - 80
    volumes:
      - ./src:/app
    ports:
      - 8000:80
    depends_on:
      - db
    links:
      - db
    command: ["uvicorn", "drivers.rest.main:app", "--host", "0.0.0.0", "--port", "80", "--reload"]
    environment:
      DATABASE_HOSTNAME: db
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_NAME: ${DATABASE_NAME}

  telegram_bot:
    build:
      context: .
    restart: always
    expose:
      - 80
    volumes:
      - ./src:/app
    ports:
      - 5002:80
    depends_on:
      - db
    links:
      - db
    command: ["python", "-m", "drivers.bots.telegram"]
    environment:
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
      DATABASE_HOSTNAME: db
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_NAME: ${DATABASE_NAME}

  db:
    image: postgres
    restart: always
    shm_size: 128mb
    expose:
      - 5432
    ports:
      - 5432:5432
    volumes:
      - database_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}

volumes:
  database_data:
    driver: local
